### ISSUE TITLE
感谢神的恩典！

### ISSUE THREAD

**Issue by weathon** [chengduqiuyu/Prayers-and-Attention#246]
感谢神的恩典，没想到可以在GitHub发现一群基督徒！
我们现在学校要给受迫害中的教会写信，需要征集以下各位的意见，谢谢！

**Comment by chengduqiuyu** [comment]
感谢主
此条目我们将移至其它地方，望能理解.

谢谢

**Comment by weathon** [comment]
好的

**Comment by chengduqiuyu** [comment]
![image](https://user-images.githubusercontent.com/37917810/81643726-c0bf0b00-9458-11ea-828e-2d412e470717.png)

**Comment by chengduqiuyu** [comment]
![0S5A2082-min](https://user-images.githubusercontent.com/37917810/81928860-8a2fee80-9618-11ea-9b90-c256a09acf22.JPG)
